---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install:
  - gem update --system
  - gem install bundler
  - bundle update --bundler
jobs:
  include:
    - stage: typecheck
      script: bundle exec srb tc
    - stage: test
      script: bundle exec rake  
    - stage: codecheck
      script: bundle exec rubocop  